pipeline {
    agent any
    tools{
        maven 'Maven 3.5.0'
        jdk 'jdk17.0.6'
    }
     stages{
        stage('Initialize'){
            steps{
                sh '''  echo 'PATH = ${PATH}'
                        echo 'M2_HOME = ${M2_HOME}'
                   '''             
            }
        }
     }  
        
    
}
