pipeline {
    agent any
    tools{
        maven 'maven_3_5_0'
        jdk 'JDK 17.0.6'
    }
     stages{
        stage('Initialize'){
            steps{
                sh '''  echo 'PATH = ${PATH}'
                        echo 'M2_HOME = ${M2_HOME}'
                   '''             
            }
        }
     }  
        
    
}
