pipeline {
    agent any
    tools{
        maven "Maven"
        jdk "JDK"
    }
     stages{
        stage('Initialize'){
            steps{
                sh '''  echo 'PATH = ${M2_HOME}/bin:${PATH}'
                        echo 'M2_HOME = /usr/share/maven'
                   '''             
            }
        }     
         stage('clone code'){
             steps {
                  checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Mohan245/Demo-Project']])
                  echo 'code checkout'
             }
         }
        stage('Build Maven'){
            steps{
                dir('Demo-Project')
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn -B -DskipTests clean install'                
               }
            }
        }       
 }
         
   
        
    

