pipeline {
    agent any
     environment {
        DOCKERHUB_CREDENTIALS = credentials('Rayleigh-hub')
    }
    tools{
        maven "Maven"
        jdk "JDK"
    }
     stages{
        stage('Initialize'){
            steps{
                sh '''  echo 'PATH = ${M2_HOME}/bin:${PATH}'
                        echo 'M2_HOME =/opt/apache-maven-3.9.0'
                   '''             
            }
        }     
         stage('clone code'){
             steps {
                  checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Mohan245/Demo-Project']])
                  echo 'code checkout'
             }
         }
        stage('Build Maven'){
            steps{                
                dir('DevOps-AutomationDemo'){
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn -B -DskipTests clean install'            
                 
                }
               }         
            }
         stage('Build Docker image'){
             steps{
                 sh 'docker build -t rayleigh0/Hello-Jenkins-Image:$BUILD_NUMBER .'
             }
         }
         stage(' Dockerhub login') {
             steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
             }
         }
         stage(' push image to hub') {
             steps{
                 sh 'docker push rayleigh0/Hello-Jenkins-Image:$BUILD_NUMBER'
             }
         }        
         
        }       
 }
post {
        always {
            sh 'docker logout'
        }
   }

         
   
        
    

